### ISSUE TITLE
&amp; entity in iframe url

### ISSUE THREAD

**Issue by shbchk** [happycog/Antenna#35]
Hello!

Thank you for this amazing addon!

I have an issue. 

Template tag:
```
{exp:antenna url='{video_url}' max_width="700" max_height="500" vimeo_title='false' vimeo_byline='false' vimeo_portrait='false' vimeo_autoplay='true' cache_minutes='0' youtube_autoplay='1' youtube_rel='0' youtube_showinfo ='0'}
<div class="embed_container">{embed_code}</div>
{/exp:antenna}
```
HTML output:
 
`<iframe src="https://player.vimeo.com/video/209895447?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1&amp;app_id=122963" frameborder="0" allow="autoplay; fullscreen" allowfullscreen title="Shock Therapy"></iframe>`

Am i doing something not right? Why i'm getting `&amp;` instead of `&` in iframe url?

_EE 6.0.0-rc1_

**Comment by mrw** [comment]
Hi @shbchk - those are HTML entities for the ampersands, which should work just fine in the attribute values and are valid HTML ways to output that. It shouldn't impact the video rendering. Let us know if you have any other trouble!
